language: objective-c
xcode_workspace: TBODeveloperOverlay.xcworkspace
xcode_scheme: TBODeveloperOverlay
xcode_sdk: iphonesimulator
osx_image: xcode7.2

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'

install:
  - gem install danger

before_script:
  - export LANG=en_US.UTF-8
  - danger