# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TBODeveloperOverlay Example iOS' do
  platform :ios, '9.3'
  use_frameworks!
  inhibit_all_warnings!
  pod 'TBODeveloperOverlay', path: '../../'
end
